name: PHP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Validate composer.json and composer.lock
      run: composer validate --strict
      working-directory: backend
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
      working-directory: backend
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      working-directory: backend
    - name: Check lint
      run: ./sniffer-check.sh
      working-directory: backend

